#!/usr/bin/env python3
"""Generate an unrolled fixed-modulus ExSuwako reducer plugin."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


WORD_BITS = 64


def parse_taps(value: str, m: int) -> list[int]:
    if value == "-":
        return []
    try:
        taps = [int(part) for part in value.split(",")]
    except ValueError as error:
        raise ValueError("taps must be comma-separated integers") from error
    if any(tap < 0 or tap >= m for tap in taps):
        raise ValueError("every tap must lie in [0,m)")
    if any(left >= right for left, right in zip(taps, taps[1:])):
        raise ValueError("taps must be strictly increasing")
    return taps


def _right_shift_expression(dst: int, shift: int) -> str:
    word_offset, bit_offset = divmod(shift, WORD_BITS)
    source = dst + word_offset
    if bit_offset == 0:
        return f"state[{source}]"
    return (
        f"(state[{source}] >> {bit_offset}) ^ "
        f"(state[{source + 1}] << {WORD_BITS - bit_offset})"
    )


def _left_shift_expression(dst: int, tap: int) -> str | None:
    word_offset, bit_offset = divmod(tap, WORD_BITS)
    if word_offset > dst:
        return None
    source = dst - word_offset
    if bit_offset == 0:
        return f"state[{source}]"
    expression = f"state[{source}] << {bit_offset}"
    if source > 0:
        expression += f" ^ state[{source - 1}] >> {WORD_BITS - bit_offset}"
    return f"({expression})"


def generate_gs_source(m: int, taps: list[int]) -> str:
    if m <= 0:
        raise ValueError("m must be positive")
    parse_taps(",".join(map(str, taps)) if taps else "-", m)
    state_words = (m + WORD_BITS - 1) // WORD_BITS
    input_words = (2 * m + WORD_BITS - 1) // WORD_BITS
    high_word, high_bits = divmod(m, WORD_BITS)
    lines = [
        "/* Generated by generate_fixed_reducer.py; do not edit. */",
        '#include "generated.h"',
        "",
        f'_Static_assert(WORD_BITS == {WORD_BITS}, "generated word width mismatch");',
        f"enum {{ GENERATED_M = {m}, GENERATED_STATE_WORDS = {state_words} }};",
        "typedef struct { word_t state[GENERATED_STATE_WORDS + 1]; } fixed_plan;",
        "",
    ]
    if taps:
        lines.append(
            "static const size_t fixed_taps[] = {"
            + ", ".join(map(str, taps))
            + "};"
        )
    else:
        lines.append("static const size_t fixed_taps[] = {0};")
    lines.extend(
        [
            "",
            "static void *fixed_plan_create(void) {",
            "    return calloc(1, sizeof(fixed_plan));",
            "}",
            "",
            "static void fixed_plan_destroy(void *opaque) { free(opaque); }",
            "",
            "static size_t fixed_plan_storage_bytes(const void *opaque) {",
            "    return opaque ? sizeof(fixed_plan) : 0;",
            "}",
            "",
            "static void fixed_reduce_into(const poly_t *input, void *opaque,",
            "                              poly_t *output) {",
            "    fixed_plan *plan = opaque;",
            "    word_t *state = plan->state;",
            "    if (output->n < GENERATED_STATE_WORDS)",
            '        die("generated output buffer is too small");',
        ]
    )

    for dst in range(state_words):
        source = dst + high_word
        terms: list[str] = []
        if source < input_words:
            terms.append(
                f"(input->n > {source} ? input->v[{source}] >> {high_bits} : 0)"
            )
        if high_bits and source + 1 < input_words:
            terms.append(
                f"(input->n > {source + 1} ? input->v[{source + 1}] "
                f"<< {WORD_BITS - high_bits} : 0)"
            )
        lines.append(f"    state[{dst}] = " + (" ^ ".join(terms) or "0") + ";")
    lines.append(f"    state[{state_words}] = 0;")

    factor = 1
    stage = 0
    while True:
        shifts = sorted(
            factor * (m - tap)
            for tap in taps
            if tap != 0 and factor * (m - tap) < m
        )
        if not shifts:
            break
        affected_words = (m - min(shifts) + WORD_BITS - 1) // WORD_BITS
        lines.append(f"    /* feedback stage {stage}: scale {factor} */")
        lines.append("    {")
        lines.append("        word_t acc;")
        for dst in range(affected_words):
            lines.append(f"        acc = state[{dst}];")
            for shift in shifts:
                if shift // WORD_BITS >= state_words - dst:
                    break
                lines.append(
                    f"        acc ^= {_right_shift_expression(dst, shift)};"
                )
            lines.append(f"        state[{dst}] = acc;")
        lines.append("    }")
        factor *= 2
        stage += 1

    lines.append("    /* low-part assembly */")
    lines.append("    {")
    lines.append("        word_t acc;")
    for dst in range(state_words):
        lines.append(
            f"        acc = input->n > {dst} ? input->v[{dst}] : 0;"
        )
        for tap in taps:
            expression = _left_shift_expression(dst, tap)
            if expression is not None:
                lines.append(f"        acc ^= {expression};")
        lines.append(f"        output->v[{dst}] = acc;")
    lines.append("    }")
    lines.extend(
        [
            "    for (size_t i = GENERATED_STATE_WORDS; i < output->n; ++i)",
            "        output->v[i] = 0;",
        ]
    )
    top_bits = m % WORD_BITS
    if top_bits:
        mask = (1 << top_bits) - 1
        lines.append(
            f"    output->v[GENERATED_STATE_WORDS - 1] &= "
            f"(word_t)0x{mask:x}UL;"
        )
    lines.extend(
        [
            "}",
            "",
            "static const generated_plugin_v1 plugin = {",
            "    .abi_version = EXSUWAKO_GENERATED_ABI_V1,",
            "    .m = GENERATED_M,",
            f"    .tap_count = {len(taps)},",
            "    .taps = fixed_taps,",
            "    .plan_create = fixed_plan_create,",
            "    .plan_destroy = fixed_plan_destroy,",
            "    .plan_storage_bytes = fixed_plan_storage_bytes,",
            "    .reduce_into = fixed_reduce_into,",
            "};",
            "",
            "EXSUWAKO_GENERATED_EXPORT",
            "const generated_plugin_v1 *exsuwako_generated_plugin_v1(void) {",
            "    return &plugin;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def generate_lopez_dahab_source(m: int, taps: list[int]) -> str:
    if m <= WORD_BITS:
        raise ValueError("Lopez-Dahab requires m greater than one word")
    parse_taps(",".join(map(str, taps)) if taps else "-", m)
    if taps and max(taps) >= m - WORD_BITS:
        raise ValueError("Lopez-Dahab requires deg(q) < m-W")

    state_words = (m + WORD_BITS - 1) // WORD_BITS
    input_words = (2 * m + WORD_BITS - 1) // WORD_BITS
    lines = [
        "/* Generated Lopez-Dahab Algorithm 2; do not edit. */",
        '#include "generated.h"',
        "",
        f'_Static_assert(WORD_BITS == {WORD_BITS}, "generated word width mismatch");',
        f"enum {{ GENERATED_M = {m}, GENERATED_STATE_WORDS = {state_words},",
        f"       GENERATED_INPUT_WORDS = {input_words} }};",
        "typedef struct { word_t work[GENERATED_INPUT_WORDS]; } fixed_plan;",
        "",
        "static const size_t fixed_taps[] = {"
        + (", ".join(map(str, taps)) if taps else "0")
        + "};",
        "",
        "static void *fixed_plan_create(void) {",
        "    return calloc(1, sizeof(fixed_plan));",
        "}",
        "",
        "static void fixed_plan_destroy(void *opaque) { free(opaque); }",
        "",
        "static size_t fixed_plan_storage_bytes(const void *opaque) {",
        "    return opaque ? sizeof(fixed_plan) : 0;",
        "}",
        "",
        "static void fixed_reduce_into(const poly_t *input, void *opaque,",
        "                              poly_t *output) {",
        "    fixed_plan *plan = opaque;",
        "    word_t *work = plan->work;",
        "    if (output->n < GENERATED_STATE_WORDS)",
        '        die("generated output buffer is too small");',
    ]
    for word in range(input_words):
        lines.append(
            f"    work[{word}] = input->n > {word} ? input->v[{word}] : 0;"
        )

    for source_word in range(input_words - 1, state_words - 1, -1):
        lines.extend(
            [
                f"    /* Cancel full high word {source_word}. */",
                "    {",
                f"        word_t top = work[{source_word}];",
                f"        work[{source_word}] = 0;",
            ]
        )
        displacement = source_word * WORD_BITS - m
        for tap in taps:
            shift = displacement + tap
            target, bits = divmod(shift, WORD_BITS)
            lines.append(f"        work[{target}] ^= top << {bits};")
            if bits:
                lines.append(
                    f"        work[{target + 1}] ^= top >> {WORD_BITS - bits};"
                )
        lines.append("    }")

    top_bits = m % WORD_BITS
    if top_bits:
        mask = (1 << top_bits) - 1
        lines.extend(
            [
                "    /* Cancel the final partial-word overflow. */",
                "    {",
                f"        word_t top = work[{state_words - 1}] >> {top_bits};",
                f"        work[{state_words - 1}] &= (word_t)0x{mask:x}UL;",
            ]
        )
        for tap in taps:
            target, bits = divmod(tap, WORD_BITS)
            lines.append(f"        work[{target}] ^= top << {bits};")
            if bits:
                lines.append(
                    f"        work[{target + 1}] ^= top >> {WORD_BITS - bits};"
                )
        lines.append("    }")

    for word in range(state_words):
        lines.append(f"    output->v[{word}] = work[{word}];")
    lines.extend(
        [
            "    for (size_t i = GENERATED_STATE_WORDS; i < output->n; ++i)",
            "        output->v[i] = 0;",
            "}",
            "",
            "static const generated_plugin_v1 plugin = {",
            "    .abi_version = EXSUWAKO_GENERATED_ABI_V1,",
            "    .m = GENERATED_M,",
            f"    .tap_count = {len(taps)},",
            "    .taps = fixed_taps,",
            "    .plan_create = fixed_plan_create,",
            "    .plan_destroy = fixed_plan_destroy,",
            "    .plan_storage_bytes = fixed_plan_storage_bytes,",
            "    .reduce_into = fixed_reduce_into,",
            "};",
            "",
            "EXSUWAKO_GENERATED_EXPORT",
            "const generated_plugin_v1 *exsuwako_generated_plugin_v1(void) {",
            "    return &plugin;",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def generate_source(m: int, taps: list[int], algorithm: str = "gs") -> str:
    if algorithm == "gs":
        return generate_gs_source(m, taps)
    if algorithm == "lopez-dahab":
        return generate_lopez_dahab_source(m, taps)
    raise ValueError(f"unknown generated algorithm: {algorithm}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--m", type=int, required=True)
    parser.add_argument("--taps", required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--algorithm", choices=["gs", "lopez-dahab"], default="gs"
    )
    args = parser.parse_args()
    taps = parse_taps(args.taps, args.m)
    source = generate_source(args.m, taps, args.algorithm)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8")
    print(json.dumps({"m": args.m, "taps": taps, "source_bytes": len(source.encode())}))


if __name__ == "__main__":
    main()
